site_name: "Vesta Lab – Storage"
repo_url:  "https://github.com/iFezGez/storage"

docs_dir: .
site_dir: ../storage_site  

theme:
  name: material
markdown_extensions: [admonition, codehilite, toc]


nav:
  - Overview: README.md

  - TrueNAS SCALE 24.04 (bare-metal):
      - Installation: truenas/scale/bare-metal/docs/installation.md
      - VLAN Networking: truenas/scale/bare-metal/docs/vlan_networking.md
      - Pool Configuration: truenas/scale/bare-metal/docs/pool_config.md
      - Datasets: truenas/scale/bare-metal/docs/datasets.md
      - Snapshots & Rollback:
          - Periodic Snapshots: truenas/scale/bare-metal/docs/snapshots.md
          - Snapshot Restoration: truenas/scale/bare-metal/docs/snapshot_restoration.md
      - Shares:
          - SMB / NFS: truenas/scale/bare-metal/docs/smb_shares.md
          - Windows Access: truenas/scale/bare-metal/docs/windows_file_access.md
          - NFS Export: truenas/scale/bare-metal/docs/nfs_exports.md
      - Scheduled Jobs:
          - Scheduled Backups: truenas/scale/bare-metal/docs/scheduled_backups.md
          - Cloud-Sync Tasks: truenas/scale/bare-metal/docs/cloud_sync.md
      - Permissions & ACL: truenas/scale/bare-metal/docs/permissions.md

  - Nextcloud (placeholder):
      - Overview: nextcloud/README.md
