site_name: "K8 Hybrid Lab"
repo_url:  "https://github.com/iFezGez/k8_clauster"
docs_dir:  docs

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc

nav:
  - Home: index.md
  - K8 Hybrid Lab:
      - Overview: k8/hybrid/overview.md
      - Phase 1 - Bootstrap Node 1: k8/hybrid/phase1-bootstrap-node1.md
      - Phase 2 - Join Nodes: k8/hybrid/phase2-join-nodes.md
      - Phase 3 - Tailscale + Oracle: k8/hybrid/phase3-tailscale-oracle.md
      - Phase 4 - Metrics: k8/hybrid/phase4-observability.md
      
