site_name: "TrueNAS SCALE 24.04 docs"
repo_url:  "https://github.com/ifezgez/storage"
docs_dir:  docs

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc

nav:
  - Home: index.md

  - TrueNAS SCALE 24.04 (bare-metal):
      - Installation: truenas/scale/24.04/bare-metal/docs/installation.md
      - Networking:   truenas/scale/24.04/bare-metal/docs/vlan_networking.md
      - Dataset Layout: truenas/scale/24.04/bare-metal/docs/datasets.md
      - Pool Configuration: truenas/scale/24.04/bare-metal/docs/pool_config.md
      - Snapshots:   truenas/scale/24.04/bare-metal/docs/snapshots.md
      - Snapshot Restoration: truenas/scale/24.04/bare-metal/docs/snapshot_restoration.md
      - Cloud Sync:  truenas/scale/24.04/bare-metal/docs/cloud_sync.md
      - Scheduled Backups: truenas/scale/24.04/bare-metal/docs/scheduled_backups.md
      - SMB / NFS Shares:  truenas/scale/24.04/bare-metal/docs/smb_shares.md
      - NFS Exports:       truenas/scale/24.04/bare-metal/docs/nfs_exports.md
      - Permissions & ACL: truenas/scale/24.04/bare-metal/docs/permissions.md
      - Windows File Access: truenas/scale/24.04/bare-metal/docs/windows_file_access.md
      